spring.application.name=dentista
spring.datasource.url=jdbc:postgresql://localhost:5432/Dentistas
spring.datasource.username=postgres
spring.datasource.password=jujuba_verde

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true